### ISSUE TITLE
Archive/Delete this repo

### ISSUE THREAD

**Issue by osterman** [cloudposse/helm-chart-scaffolding#7]
## what
* This should be called something other than scaffolding
* It should be something like to "monochart" or "charts/universal", "charts/declarative"

## why
* As scaffolding, this is a very verbose and complex chart

**Comment by osterman** [comment]
I think we should just archive/delete. Instead do https://github.com/cloudposse/helm-chart-scaffolding/issues/9

**Comment by alebabai** [comment]
@osterman could you archive this repo?

**Comment by osterman** [comment]
Will do

**Comment by osterman** [comment]
See: https://github.com/cloudposse/charts/tree/master/incubator/monochart
